buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.1'
        classpath 'com.chaquo.python:gradle:17.0.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
